apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
data:
  env.js: |
    window.__env = {
      KEYCLOAK_URL: "http://localhost:30090",
      KEYCLOAK_REALM: "dev-realm",
      KEYCLOAK_CLIENT_ID: "kuala"
    };
